/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recuperacion;

import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class Ejercicio007 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio007
     */
    public Ejercicio007() {
        initComponents();
    }
    
    /*
    Cierta empresa proporciona un bono mensual a sus trabajadores, el cual puede 
    ser por su antigüedad o bien por el monto de su sueldo (el que sea mayor),
    de la siguiente forma: Cuando la antigüedad es mayor a 2 años pero menor a 
    5, se otorga 20 % de su sueldo; cuando es de 5 años o más, 30 %. Ahora bien,
    el bono por concepto de sueldo, si éste es menor a $1000, se da 25 % de
    éste, cuando éste es mayor a $1000, pero menor o igual a $3500, se otorga
    15% de su sueldo, para más de $3500. 10%. 
    */
    
    //Métodos
    public float aumentoAntiguedad(int antiguedad, float sueldo){
        if (antiguedad > 2 && antiguedad < 5) sueldo = sueldo * 0.20f;
        else if (antiguedad >= 5) sueldo = sueldo * 0.30f;
        else sueldo = 0;
        return sueldo;
    }
    
    public float aumentoSueldo(float sueldo){
        if (sueldo <= 1000) sueldo = sueldo * 0.25f;
        else if (sueldo > 1000 && sueldo <= 3500) sueldo = sueldo * 0.15f;
        else sueldo = sueldo * 0.10f;
        return sueldo;
    }
    
    public float determinarAumento(int antiguedad, float sueldo){
        if (aumentoAntiguedad(antiguedad,sueldo) > aumentoSueldo(sueldo)){
            sueldo = aumentoAntiguedad(antiguedad,sueldo);
        }
        else{
            sueldo = aumentoSueldo(sueldo);
        }
        return sueldo;
    }

    public void mostrarAumento(int antiguedad, float sueldo){
        
        JOptionPane.showMessageDialog(null, "Tu sueldo actual es de $" + sueldo +
                "\nTu aumento es de $" + determinarAumento(antiguedad, sueldo) + 
                "\nTu nuevo sueldo es $" + (sueldo+determinarAumento(antiguedad, sueldo)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        txtAntiguedad = new javax.swing.JTextField();
        btnCalcularAumento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Calcular aumento de sueldo.");

        jLabel2.setText("Antigüedad:");

        jLabel3.setText("Sueldo:");

        btnCalcularAumento.setText("Calcular Aumento");
        btnCalcularAumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(btnCalcularAumento)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnCalcularAumento)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularAumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAumentoActionPerformed
        
        int antiguedad = Integer.parseInt(txtAntiguedad.getText().toString());
        float sueldo = Float.parseFloat(txtSueldo.getText().toString());
        
        mostrarAumento(antiguedad, sueldo);
                
        
    }//GEN-LAST:event_btnCalcularAumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio007.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio007.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio007.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio007.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio007().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularAumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAntiguedad;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
