/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recuperacion;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class Ejercicio008 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio008
     */
    public Ejercicio008() {
        initComponents();
        
    }

    DecimalFormat f = new DecimalFormat("#0.00");
    
    /*
    Una compañía de seguros para autos ofrece dos tipos de póliza: cobertura 
    amplia (A) y daños a terceros (B). Para el plan A, la cuota base es de
    $1,200, y para el B, de $950. A ambos planes se les carga 10% del costo si 
    la persona que conduce tiene por hábito beber alcohol, 5% si utiliza lentes,
    5% si padece alguna enfermedad –como deficiencia cardiaca o diabetes–, y si
    tiene más de 40 años, se le carga 20%, de lo contrario sólo 10%. Todos estos 
    cargos se realizan sobre el costo base.
    */
    
    //Metodos
    public int costoSeguro(){
        int costoSeguro = 0;
        
        if(rbtCoberturaAmplia.isSelected()){
            costoSeguro = 1200;
        }
        
        if(rbtDaniosTerceros.isSelected()){
            costoSeguro = 950;
        }
        
        return costoSeguro;
    }
    
    public float primaAlcohol(){
        
        float primaAlcohol = 0;
        
        if (cmbAlchol.getSelectedIndex() == 0){
            primaAlcohol = costoSeguro() * 0.10f;
        }
        else{
            primaAlcohol = 0;
        }
        
        return primaAlcohol;
        
    }
    
    public float primaLentes(){
        float primaLentes = 0;
        
        if (cmbLentes.getSelectedIndex() == 0){
            primaLentes = costoSeguro() * 0.05f;
        }
        else{
            primaLentes = 0;
        }
        return primaLentes;
    }
    
    public float primaEnfermedad(){
        float primaEnfermedad = 0;
        
        if (cmbEnfermedad.getSelectedIndex() == 0){
            primaEnfermedad = costoSeguro() * 0.05f;
        }
        else{
            primaEnfermedad = 0;
        }
        
        return primaEnfermedad;
    }
    
    public float primaEdad(int edad){
        float primaEdad = edad>40?costoSeguro()*0.20f:costoSeguro()*0.10f;
        return primaEdad;
    }
    
    public float totalSeguro(int edad){
        float totalSeguro =
                costoSeguro() +
                primaAlcohol() +
                primaLentes() +
                primaEnfermedad() +
                primaEdad(edad);
        return totalSeguro;
    }
    
    public void cotizarSeguro(int edad){
        
        JOptionPane.showMessageDialog(null,
                "El costo de su póliza base es de \t\t$" + f.format(costoSeguro()) + 
                "\nPrima de alcohol \t\t\t$" +  f.format(primaAlcohol()) + 
                "\nPrima de lentes \t\t\t$" + f.format(primaLentes()) + 
                "\nPrima enfermedad \t\t\t$" + f.format(primaEnfermedad()) + 
                "\nPrima edad \t\t\t\t$" + f.format(primaEdad(edad)) + 
                "\nCosto total póliza \t\t\t$" + f.format(totalSeguro(edad)));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbtCoberturaAmplia = new javax.swing.JRadioButton();
        rbtDaniosTerceros = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        cmbLentes = new javax.swing.JComboBox<>();
        cmbAlchol = new javax.swing.JComboBox<>();
        cmbEnfermedad = new javax.swing.JComboBox<>();
        btnCotizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Costo Póliza de seguro de auto");

        jLabel2.setText("Tipo de póliza:");

        buttonGroup1.add(rbtCoberturaAmplia);
        rbtCoberturaAmplia.setText("Cobertura Amplia");

        buttonGroup1.add(rbtDaniosTerceros);
        rbtDaniosTerceros.setText("Daños a terceros");

        jLabel3.setText("¿Consume alcohol?");

        jLabel4.setText("¿Usa lentes?");

        jLabel5.setText("¿Padece alguna enfermedad como: Deficiencia cardiaca ó diabetes?");

        jLabel6.setText("Edad:");

        cmbLentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));

        cmbAlchol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));

        cmbEnfermedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));

        btnCotizar.setText("Cotizar");
        btnCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(rbtCoberturaAmplia)
                            .addComponent(rbtDaniosTerceros)
                            .addComponent(jLabel3)
                            .addComponent(cmbLentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cmbAlchol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cmbEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCotizar)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtCoberturaAmplia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtDaniosTerceros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbAlchol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbLentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCotizar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizarActionPerformed
        
        int edad = Integer.parseInt(txtEdad.getText().toString());
        
        cotizarSeguro(edad);
    }//GEN-LAST:event_btnCotizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio008.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio008.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio008.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio008.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio008().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCotizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbAlchol;
    private javax.swing.JComboBox<String> cmbEnfermedad;
    private javax.swing.JComboBox<String> cmbLentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbtCoberturaAmplia;
    private javax.swing.JRadioButton rbtDaniosTerceros;
    private javax.swing.JTextField txtEdad;
    // End of variables declaration//GEN-END:variables
}
