/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author gustavo
 */
public class FrmImitador extends javax.swing.JFrame {

    /**
     * Creates new form FrmImitador
     */
    public FrmImitador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOriginal = new javax.swing.ButtonGroup();
        bgEspejo = new javax.swing.ButtonGroup();
        rbtOpcion1Original = new javax.swing.JRadioButton();
        rbtOpcion2Original = new javax.swing.JRadioButton();
        rbtOpcion3Original = new javax.swing.JRadioButton();
        chkOpcion4Original = new javax.swing.JCheckBox();
        chkOpcion5Original = new javax.swing.JCheckBox();
        chkOpcion6Original = new javax.swing.JCheckBox();
        txtOriginal = new javax.swing.JTextField();
        cboOriginal = new javax.swing.JComboBox<>();
        spnOriginal = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        rbtOpcion1Espejo = new javax.swing.JRadioButton();
        rbtOpcion2Espejo = new javax.swing.JRadioButton();
        rbtOpcion3Espejo = new javax.swing.JRadioButton();
        chkOpcion4Espejo = new javax.swing.JCheckBox();
        chkOpcion5Espejo = new javax.swing.JCheckBox();
        chkOpcion6Espejo = new javax.swing.JCheckBox();
        txtEspejo = new javax.swing.JTextField();
        cboEspejo = new javax.swing.JComboBox<>();
        spnEspejo = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imitador");

        bgOriginal.add(rbtOpcion1Original);
        rbtOpcion1Original.setText("Opción 1");
        rbtOpcion1Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOpcion1OriginalActionPerformed(evt);
            }
        });

        bgOriginal.add(rbtOpcion2Original);
        rbtOpcion2Original.setText("Opción 2");
        rbtOpcion2Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOpcion2OriginalActionPerformed(evt);
            }
        });

        bgOriginal.add(rbtOpcion3Original);
        rbtOpcion3Original.setText("Opción 3");
        rbtOpcion3Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOpcion3OriginalActionPerformed(evt);
            }
        });

        chkOpcion4Original.setText("Opción 4");
        chkOpcion4Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpcion4OriginalActionPerformed(evt);
            }
        });

        chkOpcion5Original.setText("Opción 5");
        chkOpcion5Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpcion5OriginalActionPerformed(evt);
            }
        });

        chkOpcion6Original.setText("Opción 6");
        chkOpcion6Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpcion6OriginalActionPerformed(evt);
            }
        });

        txtOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOriginalActionPerformed(evt);
            }
        });
        txtOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOriginalKeyTyped(evt);
            }
        });

        cboOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboOriginal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOriginalItemStateChanged(evt);
            }
        });

        spnOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnOriginalStateChanged(evt);
            }
        });

        jLabel1.setText("Original");

        jLabel2.setText("Espejo");

        bgEspejo.add(rbtOpcion1Espejo);
        rbtOpcion1Espejo.setText("Opción 1");
        rbtOpcion1Espejo.setEnabled(false);
        rbtOpcion1Espejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOpcion1EspejoActionPerformed(evt);
            }
        });

        bgEspejo.add(rbtOpcion2Espejo);
        rbtOpcion2Espejo.setText("Opción 2");
        rbtOpcion2Espejo.setEnabled(false);

        bgEspejo.add(rbtOpcion3Espejo);
        rbtOpcion3Espejo.setText("Opción 3");
        rbtOpcion3Espejo.setEnabled(false);

        chkOpcion4Espejo.setText("Opción 4");
        chkOpcion4Espejo.setEnabled(false);

        chkOpcion5Espejo.setText("Opción 5");
        chkOpcion5Espejo.setEnabled(false);
        chkOpcion5Espejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOpcion5EspejoActionPerformed(evt);
            }
        });

        chkOpcion6Espejo.setText("Opción 6");
        chkOpcion6Espejo.setEnabled(false);

        txtEspejo.setEnabled(false);

        cboEspejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboEspejo.setEnabled(false);

        spnEspejo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtOpcion1Original)
                                    .addComponent(rbtOpcion2Original)
                                    .addComponent(rbtOpcion3Original))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkOpcion4Original)
                                    .addComponent(chkOpcion5Original)
                                    .addComponent(chkOpcion6Original))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOriginal)
                                    .addComponent(cboOriginal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spnOriginal)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtOpcion1Espejo)
                                    .addComponent(rbtOpcion2Espejo)
                                    .addComponent(rbtOpcion3Espejo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkOpcion4Espejo)
                                    .addComponent(chkOpcion5Espejo)
                                    .addComponent(chkOpcion6Espejo))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboEspejo, javax.swing.GroupLayout.Alignment.LEADING, 0, 202, Short.MAX_VALUE)
                                    .addComponent(txtEspejo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnEspejo, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rbtOpcion1Original)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtOpcion2Original))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkOpcion4Original, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkOpcion5Original))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkOpcion6Original)
                            .addComponent(rbtOpcion3Original))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rbtOpcion1Espejo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtOpcion2Espejo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkOpcion4Espejo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkOpcion5Espejo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkOpcion6Espejo)
                            .addComponent(rbtOpcion3Espejo))))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkOpcion5EspejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpcion5EspejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOpcion5EspejoActionPerformed

    private void rbtOpcion1EspejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOpcion1EspejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtOpcion1EspejoActionPerformed

    private void rbtOpcion1OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOpcion1OriginalActionPerformed
        rbtOpcion1Espejo.setSelected(true);
    }//GEN-LAST:event_rbtOpcion1OriginalActionPerformed

    private void rbtOpcion2OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOpcion2OriginalActionPerformed
        rbtOpcion2Espejo.setSelected(true);
    }//GEN-LAST:event_rbtOpcion2OriginalActionPerformed

    private void rbtOpcion3OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOpcion3OriginalActionPerformed
        rbtOpcion3Espejo.setSelected(true);
    }//GEN-LAST:event_rbtOpcion3OriginalActionPerformed

    private void chkOpcion4OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpcion4OriginalActionPerformed
        
      chkOpcion4Espejo.setSelected(chkOpcion4Original.isSelected());       
        
    }//GEN-LAST:event_chkOpcion4OriginalActionPerformed

    private void chkOpcion5OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpcion5OriginalActionPerformed
        
        chkOpcion5Espejo.setSelected(chkOpcion5Original.isSelected());
    }//GEN-LAST:event_chkOpcion5OriginalActionPerformed

    private void chkOpcion6OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOpcion6OriginalActionPerformed
        
        chkOpcion6Espejo.setSelected(chkOpcion6Original.isSelected());
    }//GEN-LAST:event_chkOpcion6OriginalActionPerformed

    private void txtOriginalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalKeyTyped
        txtEspejo.setText(txtOriginal.getText());
    }//GEN-LAST:event_txtOriginalKeyTyped

    private void cboOriginalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOriginalItemStateChanged
        cboEspejo.setSelectedIndex(cboOriginal.getSelectedIndex());
    }//GEN-LAST:event_cboOriginalItemStateChanged

    private void spnOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnOriginalStateChanged
        spnEspejo.setValue(spnOriginal.getValue());
    }//GEN-LAST:event_spnOriginalStateChanged

    private void txtOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOriginalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOriginalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmImitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmImitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmImitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmImitador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmImitador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEspejo;
    private javax.swing.ButtonGroup bgOriginal;
    private javax.swing.JComboBox<String> cboEspejo;
    private javax.swing.JComboBox<String> cboOriginal;
    private javax.swing.JCheckBox chkOpcion4Espejo;
    private javax.swing.JCheckBox chkOpcion4Original;
    private javax.swing.JCheckBox chkOpcion5Espejo;
    private javax.swing.JCheckBox chkOpcion5Original;
    private javax.swing.JCheckBox chkOpcion6Espejo;
    private javax.swing.JCheckBox chkOpcion6Original;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtOpcion1Espejo;
    private javax.swing.JRadioButton rbtOpcion1Original;
    private javax.swing.JRadioButton rbtOpcion2Espejo;
    private javax.swing.JRadioButton rbtOpcion2Original;
    private javax.swing.JRadioButton rbtOpcion3Espejo;
    private javax.swing.JRadioButton rbtOpcion3Original;
    private javax.swing.JSpinner spnEspejo;
    private javax.swing.JSpinner spnOriginal;
    private javax.swing.JTextField txtEspejo;
    private javax.swing.JTextField txtOriginal;
    // End of variables declaration//GEN-END:variables
}
