/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import java.net.URL;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author gustavo
 */
public class Interfaz002 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz002
     */
    public Interfaz002() {
        initComponents();
        
        ButtonGroup bg = new ButtonGroup();
        
        bg.add(rbtPig);
        bg.add(rbtMouse);
        bg.add(rbtHorse);
        bg.add(rbtSheep);
        bg.add(rbtDog);
        
        //Radio por defecto
        rbtDog.setSelected(true);
        
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/dog.jpg")));
        txtAnimal.setText("Mi animal favorito es " +rbtDog.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPig1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbtPig = new javax.swing.JRadioButton();
        rbtMouse = new javax.swing.JRadioButton();
        rbtHorse = new javax.swing.JRadioButton();
        rbtSheep = new javax.swing.JRadioButton();
        rbtDog = new javax.swing.JRadioButton();
        txtImagen = new javax.swing.JLabel();
        txtAnimal = new javax.swing.JLabel();

        txtPig1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/pig.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Animal Favorito");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Animal Favorito");

        rbtPig.setText("Pig");
        rbtPig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPigActionPerformed(evt);
            }
        });

        rbtMouse.setText("Mouse");
        rbtMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMouseActionPerformed(evt);
            }
        });

        rbtHorse.setText("Horse");
        rbtHorse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHorseActionPerformed(evt);
            }
        });

        rbtSheep.setText("Sheep");
        rbtSheep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSheepActionPerformed(evt);
            }
        });

        rbtDog.setText("Dog");
        rbtDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDogActionPerformed(evt);
            }
        });

        txtImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtPig)
                            .addComponent(rbtMouse)
                            .addComponent(rbtHorse)
                            .addComponent(rbtSheep)
                            .addComponent(rbtDog))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(rbtPig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtMouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtHorse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtSheep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtDog)
                .addGap(18, 18, 18)
                .addComponent(txtAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPigActionPerformed
       
        if(rbtPig.isSelected()){
            txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/pig.jpg")));
            txtAnimal.setText("");
        }
        
    }//GEN-LAST:event_rbtPigActionPerformed

    private void rbtMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMouseActionPerformed
        
        if(rbtMouse.isSelected()){
            txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/mouse.jpg")));
            txtAnimal.setText("");
        }
    }//GEN-LAST:event_rbtMouseActionPerformed

    private void rbtHorseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHorseActionPerformed
       
        if(rbtHorse.isSelected()){
            txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/horse.jpg")));
            txtAnimal.setText("");
        }
    }//GEN-LAST:event_rbtHorseActionPerformed

    private void rbtSheepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSheepActionPerformed
        
        if(rbtSheep.isSelected()){
            txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/oveja.jpg")));
            txtAnimal.setText("");
        }
    }//GEN-LAST:event_rbtSheepActionPerformed

    private void rbtDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDogActionPerformed
        
        if(rbtDog.isSelected()){
            txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen/dog.jpg")));
            txtAnimal.setText("Mi animal favorito es " +rbtDog.getText());
        }
    }//GEN-LAST:event_rbtDogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz002.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz002.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz002.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz002.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz002().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbtDog;
    private javax.swing.JRadioButton rbtHorse;
    private javax.swing.JRadioButton rbtMouse;
    private javax.swing.JRadioButton rbtPig;
    private javax.swing.JRadioButton rbtSheep;
    private javax.swing.JLabel txtAnimal;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JLabel txtPig1;
    // End of variables declaration//GEN-END:variables

    private ImageIcon ImagenIcon(URL resource) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
